#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#
#  datasource:
#    url: jdbc:h2:mem:hong1
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  data:
#    web:
#      pageable:
#        max-page-size: 2000
#        default-page-size: 5
#        one-indexed-parameters: true
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#
#
